# Generated by Django 6.0.2 on 2026-02-14 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_quizsession_lives_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('technical', 'Technical'), ('non-technical', 'Non-Technical')], default='technical', max_length=20),
        ),
    ]
