# Generated by Django 6.0.2 on 2026-02-15 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_alter_category_category_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('technical', 'Technical'), ('non-technical', 'Non-Technical'), ('entertainment', 'Entertainment')], default='technical', max_length=20),
        ),
    ]
