# Generated by Django 6.0.2 on 2026-02-15 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0006_alter_category_category_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
