# Generated by Django 6.0.2 on 2026-02-15 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_type', models.CharField(choices=[('bonus_marks_5', '+5 Bonus Marks'), ('bonus_marks_10', '+10 Bonus Marks'), ('free_reattempt', '1 Free Reattempt Token'), ('premium_unlock', 'Unlock Premium Topic (1 Day)'), ('points_50', '50 Reward Points'), ('points_100', '100 Reward Points'), ('double_points', 'Double Points in Next Quiz'), ('surprise_unlock', 'Surprise Quiz Unlock'), ('better_luck', 'Better Luck Next Time')], max_length=50)),
                ('is_used', models.BooleanField(default=False)),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailySpinTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('spins_used', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spin_tracks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
    ]
